import type {
  RetailDocument,
  DashboardKpi,
  DailyInsight,
  Product,
  Supplier,
} from "./types";

const STORE_ID = "store_demo_01";

export const mockSuppliers: Supplier[] = [
  { id: "sup_alpha", storeId: STORE_ID, orgId: null, name: "Alpha Distribution OOO", stir: "301234567", verified: true },
  { id: "sup_beta", storeId: STORE_ID, orgId: null, name: "Beta Trade MChJ", stir: "302345678", verified: true },
  { id: "sup_gamma", storeId: STORE_ID, orgId: null, name: "Gamma Goods", stir: "303456789", verified: false },
  { id: "sup_lazzat", storeId: STORE_ID, orgId: null, name: "Lazzat OOO", stir: "304567890", verified: true },
  { id: "sup_nestle", storeId: STORE_ID, orgId: null, name: "Nestle Uzbekistan", stir: "305678901", verified: true },
  { id: "sup_coca", storeId: STORE_ID, orgId: null, name: "Coca-Cola Bottlers", stir: "306789012", verified: true },
  { id: "sup_karim", storeId: STORE_ID, orgId: null, name: "Karim Trading MChJ", stir: "307890123", verified: true },
  { id: "sup_eskishahar", storeId: STORE_ID, orgId: null, name: "Eski Shahar Don MChJ", stir: "308901234", verified: true },
  { id: "sup_imkon", storeId: STORE_ID, orgId: null, name: "Imkon Sut OOO", stir: "309012345", verified: true },
  { id: "sup_tashkent_non", storeId: STORE_ID, orgId: null, name: "Toshkent Non Kombinati", stir: "310123456", verified: true },
  { id: "sup_mineralka", storeId: STORE_ID, orgId: null, name: "Mineralka MChJ", stir: "311234567", verified: false },
  { id: "sup_tabiat", storeId: STORE_ID, orgId: null, name: "Tabiat MChJ", stir: "312345678", verified: true },
  { id: "sup_yangihayot", storeId: STORE_ID, orgId: null, name: "Yangi Hayot Distribution", stir: "313456789", verified: true },
  { id: "sup_halyk", storeId: STORE_ID, orgId: null, name: "Halyk Trade OOO", stir: "314567890", verified: false },
  { id: "sup_marvelous", storeId: STORE_ID, orgId: null, name: "Marvelous Distribution", stir: "315678901", verified: true },
];

export const mockDocuments: RetailDocument[] = [
  {
    id: "doc_12345",
    storeId: STORE_ID,
    orgId: null,
    number: "12345",
    source: "didox",
    supplier: mockSuppliers[0],
    date: "2026-05-21T08:42:00Z",
    totalAmount: 4567800,
    status: "review",
    reviewCount: 3,
    createdAt: "2026-05-21T08:42:00Z",
    rows: [
      {
        id: "row_1",
        rawName: "Mol go'shti birinchi nav",
        mappedName: "Mol go'shti (premium)",
        mappedProductId: "p_meat_premium",
        mxik: { code: "0201301000", name: "Mol go'shti, premium kategoriya", confidence: 0.98 },
        unit: "kg",
        quantity: 15,
        price: 85000,
        total: 1275000,
        confidence: 0.98,
        status: "matched",
      },
      {
        id: "row_2",
        rawName: "Coca-Cola 0.5L plastik",
        mappedName: null,
        mappedProductId: null,
        mxik: { code: "2202100000", name: "Gazlangan ichimliklar, qadoqlangan", confidence: 0.72 },
        unit: "dona",
        quantity: 50,
        price: 7500,
        total: 375000,
        confidence: 0.72,
        status: "new",
      },
      {
        id: "row_3",
        rawName: "Hindiston choyi 100g",
        mappedName: null,
        mappedProductId: null,
        mxik: { code: "0902200000", name: "Qora choy, qadoqlangan ≤3kg", confidence: 0.43 },
        alternatives: [
          { code: "0902409000", name: "Choy yaproq, qora — boshqalar", confidence: 0.41 },
          { code: "0902200000", name: "Qora choy, qadoqlangan ≤3kg", confidence: 0.43 },
          { code: "0902100000", name: "Yashil choy, qadoqlangan ≤3kg", confidence: 0.38 },
        ],
        unit: "dona",
        quantity: 20,
        price: 12000,
        total: 240000,
        confidence: 0.43,
        status: "ambiguous",
      },
      {
        id: "row_4",
        rawName: "Sut 1L Imkon",
        mappedName: "Sut 1L Imkon (pasterizovannoy)",
        mappedProductId: "p_milk_imkon",
        mxik: { code: "0401200000", name: "Sut, pasterizovannoy 1-6%", confidence: 0.95 },
        unit: "dona",
        quantity: 30,
        price: 8500,
        total: 255000,
        confidence: 0.95,
        status: "matched",
      },
      {
        id: "row_5",
        rawName: "Non gulli",
        mappedName: "Non gulli (oddiy)",
        mappedProductId: "p_bread_gulli",
        mxik: { code: "1905900000", name: "Non va non mahsulotlari", confidence: 0.99 },
        unit: "dona",
        quantity: 40,
        price: 3500,
        total: 140000,
        confidence: 0.99,
        status: "matched",
      },
      {
        id: "row_6",
        rawName: "Suv mineral 0.5L Tashkent",
        mappedName: "Mineral suv 0.5L",
        mappedProductId: "p_water_tashkent",
        mxik: { code: "2201100000", name: "Mineral suv va gazirovkasiz suv", confidence: 0.93 },
        unit: "dona",
        quantity: 100,
        price: 3000,
        total: 300000,
        confidence: 0.93,
        status: "matched",
      },
      {
        id: "row_7",
        rawName: "Sigaret Esse Light",
        mappedName: null,
        mappedProductId: null,
        mxik: { code: "2402200000", name: "Sigaret, tutun bilan", confidence: 0.81 },
        unit: "blok",
        quantity: 5,
        price: 150000,
        total: 750000,
        confidence: 0.81,
        status: "new",
      },
      {
        id: "row_8",
        rawName: "Yog' suncha 1L",
        mappedName: "O'simlik yog'i 1L (kungaboqar)",
        mappedProductId: "p_oil_sunflower",
        mxik: { code: "1512190000", name: "Kungaboqar yog'i, rafinirovaniya", confidence: 0.91 },
        unit: "dona",
        quantity: 25,
        price: 49200,
        total: 1230000,
        confidence: 0.91,
        status: "matched",
      },
    ],
  },
  {
    id: "doc_12346",
    storeId: STORE_ID,
    orgId: null,
    number: "12346",
    source: "didox",
    supplier: mockSuppliers[1],
    date: "2026-05-21T07:15:00Z",
    totalAmount: 2845000,
    status: "approved",
    reviewCount: 0,
    createdAt: "2026-05-21T07:15:00Z",
    rows: [],
  },
  {
    id: "doc_12347",
    storeId: STORE_ID,
    orgId: null,
    number: "12347",
    source: "excel",
    supplier: mockSuppliers[2],
    date: "2026-05-20T14:30:00Z",
    totalAmount: 1245600,
    status: "pending",
    reviewCount: 5,
    createdAt: "2026-05-20T14:30:00Z",
    rows: [],
  },
];

export const mockKpi: DashboardKpi = {
  newDocumentsToday: 12,
  reviewQueueCount: 5,
  autoApprovalRate: 0.87,
  mxikErrorsToday: 3,
  trends: { newDocs: 3, accuracy: 0.04 },
};

export const mockWeeklyChart = [
  { day: "Du", count: 8 },
  { day: "Se", count: 13 },
  { day: "Ch", count: 19 },
  { day: "Pa", count: 15 },
  { day: "Ju", count: 24, today: true },
  { day: "Sh", count: 10 },
  { day: "Ya", count: 5 },
];

export const mockInsights: DailyInsight[] = [
  // 🔴 Low stock — critical (4 ta)
  {
    id: "ins_1",
    type: "low-stock",
    severity: "critical",
    title: "Coca-Cola 0.5L tugamoqda",
    body: "Hozirgi qoldiq: 3 dona. So'nggi 7 kun o'rtacha sotuv: 12/kun. Taxminan 6 soatdan keyin tugaydi.",
    productId: "p_coca_05",
    suggestedAction: { label: "50 dona buyurtma berish (Alpha Distribution, 7,500 so'm)", payload: { productId: "p_coca_05", qty: 50, supplierId: "sup_alpha" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  {
    id: "ins_2",
    type: "low-stock",
    severity: "critical",
    title: "Non gulli — qoldiq kam",
    body: "Hozirgi qoldiq: 4 dona. So'nggi 7 kun o'rtacha sotuv: 38/kun. Taxminan 3 soatda tugaydi.",
    productId: "p_bread_gulli",
    suggestedAction: { label: "80 dona buyurtma — Beta Trade, 3,500 so'm", payload: { productId: "p_bread_gulli", qty: 80, supplierId: "sup_beta" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  {
    id: "ins_3",
    type: "low-stock",
    severity: "critical",
    title: "Sigaret Esse Light — kritik daraja",
    body: "Hozirgi qoldiq: 2 blok. So'nggi 7 kun o'rtacha sotuv: 4 blok/kun. Taxminan 12 soatda tugaydi.",
    productId: "p_cig_esse",
    suggestedAction: { label: "20 blok buyurtma — Alpha Distribution, 150,000 so'm", payload: { productId: "p_cig_esse", qty: 20, supplierId: "sup_alpha" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  {
    id: "ins_4",
    type: "low-stock",
    severity: "critical",
    title: "O'simlik yog'i 1L — minimal pastida",
    body: "Hozirgi qoldiq: 6 dona. So'nggi 7 kun o'rtacha sotuv: 9/kun. Taxminan 16 soatda tugaydi.",
    productId: "p_oil_sunflower",
    suggestedAction: { label: "40 dona buyurtma — Alpha Distribution, 49,200 so'm", payload: { productId: "p_oil_sunflower", qty: 40, supplierId: "sup_alpha" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  // 💰 Price spikes (3 ta)
  {
    id: "ins_5",
    type: "price-spike",
    severity: "warning",
    title: "Coca-Cola 0.5L — Pepsi'da 18% qimmatladi",
    body: "Pepsi Distribyutor 2,800 → 3,300 so'm. Alternative: Beta Trade'da 2,950 so'm — taxmini tejov 35,000 so'm/oy.",
    productId: "p_coca_05",
    supplierId: "sup_beta",
    suggestedAction: { label: "Yetkazib beruvchini Beta Trade'ga almashtirish", payload: { fromSupplierId: "sup_alpha", toSupplierId: "sup_beta" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  {
    id: "ins_6",
    type: "price-spike",
    severity: "warning",
    title: "Mineral suv 0.5L — narx 12% oshdi",
    body: "Alpha Distribution 3,000 → 3,360 so'm. Gamma Goods'da 2,850 so'm — taxmini tejov 18,400 so'm/oy.",
    productId: "p_water_tashkent",
    supplierId: "sup_gamma",
    suggestedAction: { label: "Gamma Goods'ga o'tish", payload: { toSupplierId: "sup_gamma" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  {
    id: "ins_7",
    type: "price-spike",
    severity: "warning",
    title: "Mol go'shti — bozor narxi 8% oshmoqda",
    body: "Hudud bo'yicha o'rtacha narx 85,000 → 92,000 so'm/kg. Tavsiya: kelgusi 14 kunga zaxira ko'paytirish.",
    productId: "p_meat_premium",
    suggestedAction: { label: "Zaxirani 20 kg ga oshirish", payload: { productId: "p_meat_premium", qty: 20 } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  // 🔄 Reorder (4 ta)
  {
    id: "ins_8",
    type: "reorder",
    severity: "info",
    title: "Sut 1L Imkon — minimal limit yaqinlashmoqda",
    body: "Hozirgi qoldiq 8 dona, minimal 15. So'nggi kirim 2 kun avval. Alpha Distribution 1 kun yetkazib beradi.",
    productId: "p_milk_imkon",
    suggestedAction: { label: "30 dona buyurtma — Alpha Distribution, 8,500 so'm", payload: { productId: "p_milk_imkon", qty: 30, supplierId: "sup_alpha" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  {
    id: "ins_9",
    type: "reorder",
    severity: "info",
    title: "Hindiston choyi 100g — kelgusi 5 kunda tugaydi",
    body: "Hozirgi qoldiq 12 dona. So'nggi 30 kun o'rtacha sotuv: 2.4/kun. Beta Trade'dan 2 kun yetkazadi.",
    productId: "p_tea_india",
    suggestedAction: { label: "25 dona buyurtma — Beta Trade, 12,000 so'm", payload: { productId: "p_tea_india", qty: 25, supplierId: "sup_beta" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  {
    id: "ins_10",
    type: "reorder",
    severity: "info",
    title: "Mol go'shti premium — buyurtma vaqti",
    body: "Hozirgi qoldiq 5 kg, minimal 10 kg. Hafta oxiri talab yuqori bo'lishi kutilmoqda (bayram).",
    productId: "p_meat_premium",
    suggestedAction: { label: "25 kg buyurtma — Alpha Distribution, 85,000 so'm/kg", payload: { productId: "p_meat_premium", qty: 25, supplierId: "sup_alpha" } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  // 🚨 Duplicates (2 ta)
  {
    id: "ins_11",
    type: "duplicate",
    severity: "warning",
    title: "'Mol go'shti birinchi nav' va 'Mol go'shti premium'",
    body: "Ikkala kartochkada bir xil MXIK kodi (0201301000) va o'xshash narx (85,000 so'm). Bir xil mahsulot bo'lishi mumkin.",
    productId: "p_meat_premium",
    suggestedAction: { label: "Birlashtirish", payload: { productIds: ["p_meat_premium", "p_meat_first"] } },
    createdAt: "2026-05-21T09:00:00Z",
  },
  {
    id: "ins_12",
    type: "duplicate",
    severity: "warning",
    title: "'Coca-Cola 0.5L' va 'Coca-Cola 500ml plastik'",
    body: "MXIK kodlari mos (2202100000). Hajm bir xil. Operatorda 2 ta alohida karta ochilgan bo'lishi mumkin.",
    productId: "p_coca_05",
    suggestedAction: { label: "Birlashtirish", payload: { productIds: ["p_coca_05", "p_coca_500ml"] } },
    createdAt: "2026-05-21T09:00:00Z",
  },
];

// Haftalik tendentsiyalar — chart data + top movers
export const mockWeeklyTrends = {
  dailyRevenue: [
    { day: "Du", value: 8.4 },
    { day: "Se", value: 12.1 },
    { day: "Ch", value: 14.7 },
    { day: "Pa", value: 11.3 },
    { day: "Ju", value: 18.2, today: true },
    { day: "Sh", value: 9.6 },
    { day: "Ya", value: 6.8 },
  ],
  topSellers: [
    { name: "Non gulli", qty: 268, revenue: 938000, trend: 0.14 },
    { name: "Coca-Cola 0.5L", qty: 87, revenue: 652500, trend: 0.09 },
    { name: "Sut 1L Imkon", qty: 165, revenue: 1402500, trend: 0.06 },
    { name: "Mineral suv 0.5L", qty: 412, revenue: 1236000, trend: 0.21 },
    { name: "O'simlik yog'i 1L", qty: 62, revenue: 3050400, trend: -0.02 },
  ],
  decliners: [
    { name: "Hindiston choyi 100g", qty: 18, revenue: 216000, trend: -0.34 },
    { name: "Sigaret Esse Light", qty: 28, revenue: 4200000, trend: -0.18 },
    { name: "Mol go'shti premium", qty: 22, revenue: 1870000, trend: -0.11 },
  ],
};

// Distribyutor portal — mock store network (47 ta do'kon)
export interface DistributorStore {
  id: string;
  name: string;
  district: string; // Toshkent, Chilonzor / etc
  status: "active" | "slow" | "inactive";
  todayDocs: number;
  weekRevenue: number; // in so'm
  trend: number; // -1..+1
  initial: string;
}

export const mockDistributorStores: DistributorStore[] = [
  { id: "st_01", name: "Karimov MChJ", district: "Toshkent, Chilonzor", status: "inactive", todayDocs: 0, weekRevenue: 12400000, trend: -0.18, initial: "K" },
  { id: "st_02", name: "Yangi Bozor", district: "Toshkent, Yunusobod", status: "active", todayDocs: 18, weekRevenue: 64200000, trend: 0.12, initial: "Y" },
  { id: "st_03", name: "Lazzat Market", district: "Toshkent, Mirzo Ulug'bek", status: "slow", todayDocs: 4, weekRevenue: 21800000, trend: -0.03, initial: "L" },
  { id: "st_04", name: "Chilonzor Market", district: "Toshkent, Chilonzor", status: "active", todayDocs: 22, weekRevenue: 78400000, trend: 0.08, initial: "C" },
  { id: "st_05", name: "Sergeli Savdo", district: "Toshkent, Sergeli", status: "active", todayDocs: 14, weekRevenue: 38600000, trend: 0.15, initial: "S" },
  { id: "st_06", name: "Olmazor Halol", district: "Toshkent, Olmazor", status: "active", todayDocs: 11, weekRevenue: 29200000, trend: 0.04, initial: "O" },
  { id: "st_07", name: "Beruniy Plaza", district: "Toshkent, Shayxontohur", status: "active", todayDocs: 16, weekRevenue: 47100000, trend: 0.22, initial: "B" },
  { id: "st_08", name: "Mirobod Savdo", district: "Toshkent, Mirobod", status: "slow", todayDocs: 3, weekRevenue: 14800000, trend: -0.07, initial: "M" },
  { id: "st_09", name: "Yakkasaroy Market", district: "Toshkent, Yakkasaroy", status: "active", todayDocs: 19, weekRevenue: 52300000, trend: 0.11, initial: "Y" },
  { id: "st_10", name: "Uchtepa Halol", district: "Toshkent, Uchtepa", status: "active", todayDocs: 12, weekRevenue: 33700000, trend: 0.06, initial: "U" },
  { id: "st_11", name: "Yashnobod Savdo", district: "Toshkent, Yashnobod", status: "active", todayDocs: 15, weekRevenue: 41900000, trend: 0.18, initial: "Y" },
  { id: "st_12", name: "Bektemir Express", district: "Toshkent, Bektemir", status: "inactive", todayDocs: 0, weekRevenue: 8200000, trend: -0.24, initial: "B" },
];

// Distribyutor portal — top-level KPIs
export const mockDistributorKpi = {
  activeStores: 47,
  totalStores: 52,
  todayDocs: 284,
  weekRevenue: "1.2 mlrd",
  avgOrder: "4.1M",
};

export const mockProducts: Product[] = [
  { id: "p_meat_premium", storeId: STORE_ID, name: "Mol go'shti (premium)", mxik: "0201301000", unit: "kg", currentStock: 15, minStock: 10, avgPrice: 85000, lastReceivedAt: "2026-05-21T08:42:00Z" },
  { id: "p_coca_05", storeId: STORE_ID, name: "Coca-Cola 0.5L", mxik: "2202100000", unit: "dona", currentStock: 3, minStock: 20, avgPrice: 7500, lastReceivedAt: "2026-05-18T10:30:00Z" },
  { id: "p_milk_imkon", storeId: STORE_ID, name: "Sut 1L Imkon", mxik: "0401200000", unit: "dona", currentStock: 8, minStock: 15, avgPrice: 8500, lastReceivedAt: "2026-05-19T11:00:00Z" },
  { id: "p_bread_gulli", storeId: STORE_ID, name: "Non gulli", mxik: "1905900000", unit: "dona", currentStock: 42, minStock: 30, avgPrice: 3500, lastReceivedAt: "2026-05-21T08:42:00Z" },
];
